# Autogenerated wrapper script for Pathfinder_jll for x86_64-w64-mingw32
export libpathfinder

JLLWrappers.@generate_wrapper_header("Pathfinder")
JLLWrappers.@declare_library_product(libpathfinder, "libpathfinder.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpathfinder,
        "bin\\libpathfinder.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
