# Autogenerated wrapper script for Pathfinder_jll for x86_64-linux-gnu
export libpathfinder

JLLWrappers.@generate_wrapper_header("Pathfinder")
JLLWrappers.@declare_library_product(libpathfinder, "libpathfinder.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpathfinder,
        "lib/libpathfinder.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
